def print_report(metrics: dict) -> None:
    """계산된 지표를 사용자에게 보기 쉬운 형태로 출력합니다."""
    print("춘천시립도서관 GA4 트래픽 요약")
    print("--------------------------------")
    print(f"분석 기간: {metrics['period_start']} ~ {metrics['period_end']}")
    print(f"일 평균 총 사용자 수: {metrics['average_users']:.0f}명")
    print(f"총 사용자 수 합계: {metrics['total_users']:,}명")
    print(f"새 사용자 수 합계: {metrics['total_new_users']:,}명")
    print(f"세션 수 합계: {metrics['total_sessions']:,}회")
    print(f"조회수 합계: {metrics['total_views']:,}회")
    print(f"평균 세션당 조회수: {metrics['average_views_per_session']:.2f}회")
    print(f"평균 세션 시간: {metrics['average_session_time']:.1f}초")
    print()
    print(f"가장 사용자가 많은 날: {metrics['max_date']} / {metrics['max_users']:,}명")
    print(f"가장 사용자가 적은 날: {metrics['min_date']} / {metrics['min_users']:,}명")
